In [1]:
a = 5
b = 7

In [2]:
c = a + b
c

12

In [3]:
from numpy import *

In [4]:
arr = array([1, 8, 3])
arr

array([1, 8, 3])

In [5]:
arr.sort
arr

array([1, 8, 3])

In [6]:
arr

array([1, 8, 3])

In [7]:
arr.sort()
arr

array([1, 3, 8])

In [8]:
import time
time.sleep(3)

def say_hello(recipient):
    return 'Hello, {}' .format(recipient)

say_hello('Tim')

'Hello, Tim'

In [9]:
def square(x):
    return x * x

In [10]:
r = random.randint(1, 20)
y = square(r)

In [11]:
print('Sqaure of %d is %g' % (r, y))

Sqaure of 15 is 225


In [12]:
y = 44